{{- if .Values.backend.nodeportService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.nodeportService.port }}
      targetPort: {{ .Values.backend.nodeportService.targetPort }}
      {{- if .Values.backend.nodeportService.nodePort }}
      nodePort: {{ .Values.backend.nodeportService.nodePort }}
      {{- end }}
{{- end }}
