apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inspection-agent.configMapName" . }}
  labels:
    app.kubernetes.io/name: {{ include "inspection-agent.name" . }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
{{- toYaml .Values.config | nindent 4 }}
