{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspection-agent.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "inspection-agent.name" . }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  registration_token: {{ .Values.secret.registrationToken | quote }}
{{- end }}
